---
- name: update apt
  action: command /usr/bin/apt-get update

- name: install python-software-properties
  action: apt pkg=python-software-properties state=present

- name: Common - Install common packages
  apt: pkg="{{ item }}" state=latest
  with_items:
    - build-essential
    - imagemagick
    - vim
    - curl
    - git
    - wget
    - htop
    - ack-grep
    - ntp

- name: ensure user `vagrant` is part of `vboxsf` group (to access shared folder)
  user: name=vagrant groups=vboxsf append=yes

- name: Common | Set the hostname /etc/hostname
  shell: echo {{ hostname }} > /etc/hostname
  when: hostname is defined

- name: Set the hostname
  shell: hostname {{ hostname }}
  when: hostname is defined

- name: apt update
  action: apt update_cache=yes

- name: update /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ hostname }}' owner=root group=root mode=0644
