---
- name: upgrade all packages, excluding kernel
  yum:
    name: '*'
    state: latest
    exclude: kernel*

- name: Install common packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - vim
    - curl
    - git
    - wget
    - yum-utils

- name: ensure user `vagrant` is part of `vboxsf` group (to access shared folder)
  user: name=vagrant groups=vboxsf append=yes

- name: Common | Set the hostname /etc/hostname
  shell: echo {{ hostname }} > /etc/hostname
  when: hostname is defined

- name: Set the hostname
  shell: hostname {{ hostname }}
  when: hostname is defined

- name: yum update
  action: yum update_cache=yes

- name: update /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ hostname }}' owner=root group=root mode=0644
  when: hostname is defined
