---
- name: upgrade all packages, excluding kernel
  yum:
    name: '*'
    state: latest
    exclude: kernel*

- name: Install common packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - vim
    - curl
    - git
    - wget
    - yum-utils

- name: upgrade all packages, excluding kernel & foo related packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
    exclude: kernel*,foo*

- name: update /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ vagrant_hostname_telesales }}' owner=root group=root mode=0644
  when: vagrant_hostname_telesales is defined
