- name: add nginx repo
  copy:
      src: files/nginx.repo 
      dest: /etc/yum.repos.d/nginx.repo 
      mode: 0644

- name: add zend-server repo
  copy: 
    src: files/zend.repo 
    dest: /etc/yum.repos.d/zend.repo 
    mode: 0644

- name: Install Zend-Server packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - zend-server-nginx

- name: Add Zend-Server to PATH
  template: src=zend-server.sh dest=/etc/profile.d/zend-server.sh

- name: ensure php.ini memory_limit is 1024M
  lineinfile: dest=/usr/local/zend/etc/php.ini regexp='^memory_limit\s?=' line='memory_limit = 1024M'

- name: set php.ini timezone config (web)
  lineinfile: dest=/usr/local/zend/etc/php.ini regexp='^;date.timezone\s?=' line="date.timezone = \"Europe/Amsterdam\""
